### ISSUE TITLE
Event trigger

### ISSUE THREAD

**Issue by chris3ware** [3ware/workflows#183]
Use `pull_request_target` or `pull_request`.

We need to see the changes between base and head - pull_request.

But I would like to use the pr-comment feature: pull_request_target.

**Comment by chris3ware** [comment]
The docs for action state `pull_request_target` can be used without specifying the branches. Checking out the `head.sha` of the PR in pull_request_target is not recommended: https://blog.gitguardian.com/github-actions-security-cheat-sheet/

> TL;DR:  if you're using the ‘on: pull_request_target’ event in Github Actions, never check out the pull request's code. DON’T use the following:

 ```
on: pull_request_target
…
steps:
  - uses: actions/checkout@v3
    with:
      ref: ${{ github.event.pull_request.head.sha }}
```

> Explainer: when someone forks your repo and opens a pull request, there are two repos involved: the repo under your control (the target repo), and the other person's fork repo.
